scrape_configs:
  - job_name: 'BeAuthUserStaffMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:81']
        labels:
          application: 'BeAuthUserStaffApplication'